### ISSUE TITLE
Porting Monash Creative Coding Course Examples to p5

### ISSUE THREAD

**Issue by juansrx** [lmccart/p5.js-website#58]
Hello!

I an interested in your project and I want to help, so I want to port the following processing sketches from the Monash Creative Coding Course found int www.futurelearn.com to p5:

Week1:
  w1_01
  w1_02
  w1_03
  w1_04_2DGraphics

There are more sketeches from this course I'd like to port. I an looking forward to any suggestion, comment or advice.

Thank you.

**Comment by lmccart** [comment]
hi juan, just doing a little cleanup and closing this issue. thanks for all your great examples! and feel free to keep posting them on the contributed demos link. :)
